import Link from 'next/link';
import { APP_CUSTOMER_SIGN_IN_URL } from '@/lib/site-links';
const faqs = [
  ['Can our team purchase and use SyncAI?', 'Yes. SyncAI is available as an industrial AI platform. Contact us to discuss platform access, commercial scope, and onboarding for your team.'],
  ['Do we need an assessment first?', 'An assessment is an optional service. You can explore the platform or discuss purchasing directly. An assessment helps establish a reliability baseline from customer-provided exports when that is useful.'],
  ['Does SyncAI replace our maintenance systems?', 'Your systems remain the source of truth. SyncAI helps teams investigate failures, prioritize work, and retain the evidence behind decisions. Data connections and implementation requirements are confirmed for your scope.'],
  ['Who approves recommendations?', 'A named human reviews and approves operational recommendations. Your team retains authority over work and plant execution.'],
  ['How are integrations and security agreed?', 'We review your required systems, data access, hosting, and security controls before implementation. Ask for the current controls and configuration relevant to your engagement.'],
  ['How is value measured?', 'Agree a baseline, operating question, and outcome measures with your team. Track the results against that baseline; savings and ROI depend on the actual operating evidence.'],
  ['What support is available?', 'Assessments, focused pilots, and team training can support adoption. Contact us to agree the scope and support your team needs.'],
];
export default function FAQPage() { return <main id="main-content" tabIndex={-1} className="bg-ink pt-16 text-bone"><div className="mx-auto max-w-5xl px-6 py-20 sm:py-28"><p className="font-mono text-sm uppercase tracking-widest text-cyan-300">FAQ</p><h1 className="mt-6 text-4xl font-bold sm:text-6xl">Choose your next step with confidence.</h1><div className="mt-14 divide-y divide-bone/15 border-y border-bone/15">{faqs.map(([question,answer]) => <details key={question} className="py-6"><summary className="cursor-pointer text-xl font-semibold">{question}</summary><p className="mt-4 max-w-3xl leading-7 text-bone/75">{answer}</p></details>)}</div><div className="mt-12 flex flex-wrap gap-6"><a href={APP_CUSTOMER_SIGN_IN_URL} className="font-semibold text-cyan-300">Existing customers: sign in →</a><Link href="/contact" className="font-semibold text-cyan-300">Discuss platform access →</Link><Link href="/reliability-assessment" className="font-semibold text-cyan-300">Optional assessment →</Link></div></div></main>; }
